### ISSUE TITLE
Allow multiple invites to be sent to same user

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#768]
Right now, it seems as if you can only have 1 "pending" invitation to any given user. This behavior may have been intended.

Would it be possible to allow user invitations to stack on any given project? For instance, I wanted to invite someone to be a "Blinded Site Editor" on 7 PATS sites. I would rather they not be a "Blinded Project Editor" (thereby having access to all sites) since I don't want this person dabbling in the project/design setup areas.

Putting in 77.0.0 for the time being to generate some initial discussion, but this isn't a hugely pressing matter.

**Comment by remomueller** [comment]
This is due to the code that checks if invites are incompatible with each other (ie blinded and unblinded roles)

https://github.com/sleepepi/slice/blob/master/app/models/invite.rb#L121-L136

It would need to be updated to be smarter, currently it checks if the role is a project level role, or a site level role, and then clears other invites of that type.
